version: '3'
services:
  app:
    build: .
    container_name: zoo
    restart: always
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=
    depends_on:
      - mysql
  mysql:
    image: arthurmauvezin/docker-labs-mysql:latest
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=zoo
      - MYSQL_USER=root
      - MYSQL_PASSWORD=
volumes:
  db_data: {}
